name: Context Information
on:
  push:
    branches:
      - main
jobs:
  show-context:
    name: Show Context
    runs-on: ubuntu-latest
    steps:
      - name: Dump event info
        env:
          CONTEXT_ITEM: ${{ toJson(github)}}
        run: echo "Context Item = ${CONTEXT_ITEM}"
      - name: dumb Jon info
        env:
          CONTEXT_ITEM: ${{ toJson(job) }}
        run: echo "Context Item = ${CONTEXT_ITEM}"
